### ISSUE TITLE
Test from JAM

### ISSUE THREAD

**Issue by slayoffer** [vVolodya/geek-console#7]
TEST

**Screenshot:**
![jam-screenshot](https://storage.googleapis.com/jam-screenshots/b14fefda-957c-4526-ba92-2c1532b9cdf8.png)

**Full screen:**
![jam-full-url-screenshot](https://storage.googleapis.com/jam-screenshots/63d14ed0-add2-4e61-b9c6-0fb01e48904f.png)

**Website URL:**
[https://vladivostok.hh.ru/applicant/resumes?hhtmFromLabel=header&hhtmFrom=vacancy](https://vladivostok.hh.ru/applicant/resumes?hhtmFromLabel=header&hhtmFrom=vacancy)

**Device and browser info:**
Chrome 107.0.0.0 (2048x1002) | Windows 10

**Date and time:**
November 9th 2022 | 8:20am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/96576f7b-4573-43d8-994f-8bc6df0231b1](https://jam.dev/c/96576f7b-4573-43d8-994f-8bc6df0231b1)

*Captured with* *[jam.dev](https://jam.dev/)*

**Comment by vVolodya** [comment]
Thank you. Test confirmed.
